import { AuthProvider } from "@/utils/authContext";

export const metadata = {
  title: 'Link Shortener',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>{children}</body>
      </AuthProvider>
    </html>
  )
}
